export enum SocketTopics {
	FOLLOW = 'FOLLOW',
	SUBSCRIPTION = 'SUBSCRIPTION',
	SUBSCRIPTIONMESSAGE = 'SUBSCRIPTIONMESSAGE',
	ENDSUBSCRIPTION = 'ENDSUBSCRIPTION',
	CHEER = 'CHEER',
	REWARDS = 'REWARDS',
}

export enum RewardTypes {
	BEER = 'BEER',
	SHIT = 'SHIT',
}
