enum SocketTopics {
	FOLLOW = 'FOLLOW',
	SUBSCRIPTION = 'SUBSCRIPTION',
	SUBSCRIPTIONMESSAGE = 'SUBSCRIPTIONMESSAGE',
	ENDSUBSCRIPTION = 'ENDSUBSCRIPTION',
	CHEER = 'CHEER',
	REWARDS = 'REWARDS',
	RAID = 'RAID',
}

export default SocketTopics;
